# Generated by Django 2.2 on 2021-02-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kelas', models.CharField(max_length=5)),
                ('npm', models.CharField(max_length=8)),
                ('umur', models.IntegerField()),
                ('cita_cita', models.TextField()),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=50)),
            ],
        ),
    ]
